//  constants for API call to get list of products
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

//  constants for API call to get a single product
export const PRODUCT_ITEM_REQUEST = "PRODUCT_ITEM_REQUEST";
export const PRODUCT_ITEM_SUCCESS = "PRODUCT_ITEM_SUCCESS";
export const PRODUCT_ITEM_FAIL = "PRODUCT_ITEM_FAIL";

//  constants for API call for user login / logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGIN_RESET = "USER_LOGIN_RESET";

//  constants for API call for registering users
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

//  constants for API call to create a new product
export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";

//  constants for API call to create a new product
export const OFFER_CREATE_REQUEST = "OFFER_CREATE_REQUEST";
export const OFFER_CREATE_SUCCESS = "OFFER_CREATE_SUCCESS";
export const OFFER_CREATE_FAIL = "OFFER_CREATE_FAIL";
export const OFFER_CREATE_RESET = "OFFER_CREATE_RESET";

//  constants for API call to get received offers
export const OFFER_RECEIVED_REQUEST = "OFFER_RECEIVED_REQUEST";
export const OFFER_RECEIVED_SUCCESS = "OFFER_RECEIVED_SUCCESS";
export const OFFER_RECEIVED_FAIL = "OFFER_RECEIVED_FAIL";

//  constants for API call to get sent offers
export const OFFER_SENT_REQUEST = "OFFER_SENT_REQUEST";
export const OFFER_SENT_SUCCESS = "OFFER_SENT_SUCCESS";
export const OFFER_SENT_FAIL = "OFFER_SENT_FAIL";

// constants for API call to get user profile details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// constants for API call to get user profile
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const BOOKMARK_INDIV_SEARCH_FAIL = "BOOKMARK_INDIV_SEARCH_FAIL";
export const BOOKMARK_INDIV_SEARCH_REQUEST = "BOOKMARK_INDIV_SEARCH_REQUEST";
export const BOOKMARK_INDIV_SEARCH_SUCCESS = "BOOKMARK_INDIV_SEARCH_SUCCESS";
export const BOOKMARK_INDIV_SEARCH_ERROR = "BOOKMARK_INDIV_SEARCH_ERROR";

export const BOOKMARK_CREATE_REQUEST = "BOOKMARK_CREATE_REQUEST";
export const BOOKMARK_CREATE_SUCCESS = "BOOKMARK_CREATE_SUCCESS";
export const BOOKMARK_CREATE_FAIL = "BOOKMARK_CREATE_FAIL";

export const BOOKMARK_DELETE_REQUEST = "BOOKMARK_DELETE_REQUEST";
export const BOOKMARK_DELETE_SUCCESS = "BOOKMARK_DELETE_SUCCESS";
export const BOOKMARK_DELETE_FAIL = "BOOKMARK_DELETE_FAIL";

export const PRODUCT_EDIT_REQUEST = "PRODUCT_EDIT_REQUEST";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_FAIL = "PRODUCT_EDIT_FAIL";
export const PRODUCT_EDIT_RESET = "PRODUCT_EDIT_RESET";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

//  constants for API call to get bought offers
export const OFFER_BOUGHT_REQUEST = "OFFER_BOUGHT_REQUEST";
export const OFFER_BOUGHT_SUCCESS = "OFFER_BOUGHT_SUCCESS";
export const OFFER_BOUGHT_FAIL = "OFFER_BOUGHT_FAIL";

//  constants for API call to get sold offers
export const OFFER_SOLD_REQUEST = "OFFER_SOLD_REQUEST";
export const OFFER_SOLD_SUCCESS = "OFFER_SOLD_SUCCESS";
export const OFFER_SOLD_FAIL = "OFFER_SOLD_FAIL";
export const OFFER_RESPOND_REQUEST = "OFFER_RESPOND_REQUEST";
export const OFFER_RESPOND_SUCCESS = "OFFER_RESPOND_SUCCESS";
export const OFFER_RESPOND_FAIL = "OFFER_RESPOND_FAIL";
export const OFFER_RESPOND_RESET = "OFFER_RESPOND_RESET";

// constants for API call to complete offers
export const OFFER_COMPLETE_REQUEST = "OFFER_COMPLETE_REQUEST";
export const OFFER_COMPLETE_SUCCESS = "OFFER_COMPLETE_SUCCESS";
export const OFFER_COMPLETE_FAIL = "OFFER_COMPLETE_FAIL";
export const OFFER_COMPLETE_RESET = "OFFER_COMPLETE_RESET";

// constants for API call to complete offers
export const OFFER_COMPLETE_GET_REQUEST = "OFFER_COMPLETE_GET_REQUEST";
export const OFFER_COMPLETE_GET_SUCCESS = "OFFER_COMPLETE_GET_SUCCESS";
export const OFFER_COMPLETE_GET_FAIL = "OFFER_COMPLETE_GET_FAIL";
export const OFFER_COMPLETE_GET_RESET = "OFFER_COMPLETE_GET_RESET";

//  constants for API call to create a new review
export const REVIEW_CREATE_REQUEST = "REVIEW_CREATE_REQUEST";
export const REVIEW_CREATE_SUCCESS = "REVIEW_CREATE_SUCCESS";
export const REVIEW_CREATE_FAIL = "REVIEW_CREATE_FAIL";
export const REVIEW_CREATE_RESET = "REVIEW_CREATE_RESET";