const restrictedItems = [
  "sibutramine",
  "mm malia mellia xxs xtraxtrasmall",
  "spironolactone",
  "gs gorgeousleem advanced",
  "d trim obesity solution",
  "beautea slim fat burner for weight loss 10 days program",
  "chlorpheniramine",
  "frusemide",
  "piroxicam",
  "bao ling capsules (保灵丸) advance finger press therapy",
  "diclofenac",
  "tablet kuat dan tahan lama khusus untuk pria dewasa 5x lebih dahsyat",
  "cyproheptadine",
  "dexamethasone",
  "top jaya sakti gemuk sehat kapsul",
  "obat asam urat flu tulang super untuk pria dan wanita capsule",
  "lami kapsul",
  "langsing alami kapsul",
  "sildenafil",
  "4x lebih dahsyat obat kuat & tahan lama urat madu capsule",
  "obat kuat & tahan lama khusus pria dewasa maximal capsule",
  "power v extra strong tongkat ali 500mg kapsul",
  "indomethacin",
  "sendi-plus 250mg capsule",
  "seki sehat pria aprodisiak & anti impotensi sami aji capsule",
  "acetic acid",
  "acetildenafil",
  "laboratory formula healthcare series menergy™ m-essence 450mg capsule",
  "fenfluramine",
  "sin gang san langsing ayu kapsul arma",
  "phenolphthalein",
  "strychnine",
  "kangli brand tian xia di yi bang 2500mg capsule (康力牌天下第一棒)",
  "xiang shou shou shen guo shu xian wei capsule (享瘦™瘦身果蔬纤维)",
  "strong boy",
  "metformin",
  "sne amberine capsules (瘦美精华)",
  "tadalafil",
  "tianlong brand sheng wu gong ting sheng bao 2000mg capsules (天龙牌生物宫廷圣宝2000mg)",
  "jin sheng li brand huang jin shen bao 3g (金聖力牌黄金腎寳3g)",
  "aminotadalafil",
  "jinglida so young formula 200mg tablet",
  "chloropretadalafil",
  "power-plus p capsule (康乐宝)",
  "power-plus s 485mg capsule",
  "mephentermine",
  "calixir labs beline capsule (百灵宝)",
  "black ant 4600mg capsules (黑蚂蚁4600mg)",
  "bio-lissom fat-reducing capsule (輕盈素瘦身膠囊)",
  "tuo zhi lpa jian fei mei rong pian (脱脂lpa减肥美容片)",
  "han mei tang brand zuo xuan rou jian l-carnitine 400mg capsules (瀚美堂左旋肉碱)",
  "lv shou reduces fat (绿瘦第二代加强版)",
  "curvy pearl beauty slimming orange juice",
  "ibuprofen",
  "pai you ji (吸油基)",
  "blueberry with maca tongkat ali extra",
  "paracetamol",
  "super max man",
  "bull genital  male sexual stimulant",
  "bull genital male sexual stimulant (三体牛鞭)",
  "chloramphenicol",
  "imidazosagatriazinone",
  "durable ares male sexual stimulant",
  "stree overlord exceed vigra and cialis",
  "befit total garcinia cambogia",
  "fluoxetine",
  "skinny22 whitening & slimming capsule",
  "propoxyphenyl aildenafil",
  "propoxyphenyl thioaildenafil",
  "propoxyphenyl thiohydroxyhomosildenafil",
  "propoxyphenyl hydroxyhomosildenafil",
  "mr zack powerbro anda lelaki hebat",
  "hydroxyhomosildenafil",
  "hydroxythiohomosildenafil",
  "sparta x",
  "magic penis",
  "n-cyclopentyl nortadalafil",
  "amace for him 300mg/capsule",
  "starkrx performance enhancer /stark-rx /maximum strength sexual enhancer",
  "forta plus for men",
  "v12 fruit slimming",
  "vtox trim up weight loss program (威特尔健美奇天然褐藻素)",
  "montalin jamu pegal linu dan asam urat",
  "black ant king (黑蚁王)",
  "lignocaine",
  "darling peculiar hormone cream 3g (爱人药霜)",
  "france t253",
  "miramax (增粗增大丸)",
  "new max man three effectiveness",
  "african superman (非洲超人)",
  "black deity (sildenafil citrate) granule",
  "red cialis viagra",
  "bonjour (fresh peach flavour)",
  "super fat burning bomb (仟佳俪左旋肉碱减肥胶嚢)",
  "revival for men only",
  "dimethylsildenafil",
  "thiodimethylsildenafil",
  "man up now capsules",
  "xiangying (享硬瑪卡濃缩片)",
  "ji yin yu gen (基因育根™)",
  "qing tian zhu tablets (擎天柱健力片剂)",
  "shou fu ti tun jian fei jiao nang (收腹提臀减肥胶囊)",
  "caffeine",
  "you en li zi y.d.l.z zuo xuan rou jian ju jue pian l-carnitine (优恩丽姿y.d.l.z 左肉碱咀嚼片)",
  "aulura™ (奥露娜™ 减肥胶囊)",
  "li da dai dai hua jiao nang (丽达代代花胶囊)",
  "reduce weight fruta planta (水果植物减肥胶囊)",
  "dz garcinia herbal plus 500mg",
  "figure-up 100% natural",
  "surut ayu jamu herbal ramuan alami",
  "diphenhydramine",
  "xxs advance xtraxtrasmall",
  "africa black ant 2500mg capsule (非洲黑蚁王)",
  "american moxman (美国魔根)",
  "baolong brand ai jia ai 3000mg capsule (寶壟牌爱加爱)",
  "amrih sehat ramping jelita shio lie ta 500mg capsule (必力大)",
  "phenylbutazone",
  "obat tradisional amrih sehat asam urat untuk pria dan wanita capsule",
  "america cowboy 500mg capsule (美國牛仔胶囊)",
  "maxman u.s.a. america vigra 1800mg tablet",
  "prednisolone",
  "huo luo jing dan (活絡金丹)",
  "ali baba",
  "balsam pear fat loss capsule (苦瓜清脂减肥胶囊)",
  "tianxiong brand ba wang long 3000mg capsule (天雄牌霸王龙)",
  "bai wei tablet (百威)",
  "bushenzhuangyang capsule",
  "chong cao bu jing wan 1g (虫草生精丸)",
  "champ",
  "chong cao lu bian wan 9g (蟲草鹿鞭丸)",
  "canada king of sea dogs 800 mg capsule (加拿大海狗王)",
  "cattle capsule (牛寳膠囊)",
  "jin sheng li brand china vigers 2500mg capsule (金聖力牌中華偉哥)",
  "de guo jin gang pen (德国金刚喷)",
  "tian long brand da di yong shi sheng jing pian 2000mg (天龙牌大地勇士生精片)",
  "li long brand de guo hei jin gang 2800mg tablet (力龙牌德国黑金刚)",
  "dong fang bu bai 800mg tablet (东方不败强神粒)",
  "shen long sheng wu brand ding chuan tian 1200mg capsule (神龙生物牌顶穿天)",
  "french silver fox 2800mg powder (法国银狐)",
  "li long brand xin yi dai hei ma yi wang 2800mg capsule (力龙牌新一代黑螞蟻王2800mg)",
  "jian min bao jian brand huatuo 2000mg capsule (健民保健牌华佗神丹)",
  "glibenclamide",
  "huang wei lu rong 0.5g capsule (皇威鹿茸胶囊)",
  "vardenafil",
  "red spider 5ml (红蜘蛛女性口服液)",
  "li long brand hao gong fu 2500mg tablet (力龙牌好功夫)",
  "sheng yang brand huang di sheng dan 3g pill (升阳牌黄帝聖丹)",
  "high-powered spray (威の猛男用延时喷剂)",
  "procaine",
  "india god lotion spray （印度神油）",
  "pheniramine",
  "jianbu huqian wan capsule (健步虎潛丸)",
  "jinmaoshiwang 1500mg tablet (金毛狮王片)",
  "hr brand jing ba su bo jiao nang 1800mg (hr牌劲霸速勃胶囊)",
  "naproxen",
  "kangli brand jinba men 2500mg (康力牌劲霸男人)",
  "li long brand jin gang shen dan 2800mg capsule (力龙牌金刚神丹)",
  "jiu chong tian capsule (九重天)",
  "buda jin qiang bu dao 800 mg tablet (金枪不倒)",
  "kang xi da di long yang dan 1000mg capsule (康熙大第龍陽丹)",
  "zhenghao brand king of postponing spray (延时王)",
  "metronidazole",
  "lang yi hao 145mg tablet (极品狼1号)",
  "longer vaigra 1500 mg capsule (长效伟哥)",
  "hong sheng sheng wu brand  li jia li (exceed vigra and cialis 3500 mg) capsule (宏圣生物牌力加力)",
  "super power pills 1800 mg tablet (力加力)",
  "li jia li (&quot;f + f&quot; super enforcement capsule) (力加力超强生力胶囊)",
  "jin wei ge brand lang shen yi hao 800mg tablet [(金威哥) 狼神1號]",
  "kangli brand le produit fin de aphrodisiaque 2500mg capsule (康力保健牌壮阳极品一粒速效)",
  "methoxsalen",
  "thiosildenafil",
  "maxidus capsules",
  "hongkong ren he tong brand lang wang 3000mg tablet (香港仁和堂牌狼王)",
  "miraculous evil root 1200mg tablet (神奇魔根)",
  "mei guo lan jing ling (美国蓝精灵) (green)",
  "mei guo lan jing ling (美国蓝精灵) (red)",
  "li long brand mei guo mo bang 2500mg capsule (力龙牌美国魔棒)",
  "li long brand mei guo zhan shen 2500mg capsule (力龙牌美国战神)",
  "ju he tang brand mei guo zhan shen 1000mg tablet (巨和堂牌美国战神 1000mg)",
  "piperiacetildenafil",
  "tong le tang brand america viagia 2000mg tablet (同乐堂牌美国战神)",
  "baolong brand usa zhanshen 2000mg capsule (寶龍牌美国战神)",
  "tai he tang brand mei guo zhan shen 1800mg tablet (太和堂牌美国战神)",
  "mo general (猛男魔根)",
  "verapamil",
  "mei guo zhan shen wai yong shen you (美国战神外用神油)",
  "midnight express men lasting cologne",
  "meng hu bei zeng capsule (猛虎倍增)",
  "migino capsule (美人露)",
  "luquan brand nangen zengzhangsu 0.4g capsule (鹿泉牌男根增长素)",
  "jin huang jin brand nan gen jing hua su 1800mg capsule (金黄金牌男根精华素)",
  "power 1 walnut 100mg tablet (动力一号核桃素片) (green)",
  "power 1 walnut 500mg tablet (动力一号核桃素片) (pink)",
  "power 1 walnut 500mg tablet (动力一号核桃素片) (blue)",
  "posh for men only capsule (寳士情人秘膏)",
  "jin sheng li brand qiang gen bao jiao nang 500mg (金聖力牌强根宝胶囊)",
  "sheng yang brand qiang shen xiao jin wan 3g (升阳牌强肾小金丸)",
  "hongkong ren he tong brand real man 3000mg tablet",
  "sheng yang brand super penis 1800mg capsule (升阳牌超级男根)",
  "li long brand shen bai jin sheng li jiao nang 2800mg (力龙牌腎白金生力胶囊)",
  "yizheng brand super cialis 1600mg tablet (一正超级西力士)",
  "carbodenafil",
  "natural wei-ge (天然威哥)",
  "tianxiong brand super is fierce male 8000mg capsule (天雄牌超级猛男)",
  "santi scalper penis erection 0.3g capsule (三體牛鞭勃動力胶囊)",
  "jin sheng li shi bian wang 1000mg tablet (金聖力十鞭王)",
  "xin yi dai san ti niu bian bo dong li jiao nang 0.3g (新一代三體牛鞭勃動力膠囊)",
  "18 spring gel (十八春催情缩阴精华素)",
  "samsu super oil",
  "sheng jing pian (生精片)",
  "spanish fly 10ml liquid",
  "sex fairy female sexual appetite powder 3g (性精灵)",
  "tanduk rusa kuat lelaki approdisiak & anti impotensi 500mg kapsul",
  "tian di ying xiong 1200mg capsule (天地英雄)",
  "shen wei brand tian di ying xiong 2000mg capsule (神威牌天地英雄)",
  "tosan splay daito",
  "vitgo oil",
  "vimax 700mg capsule (增大丸)",
  "theophylline",
  "li zhi yuan brand qiang jing wei ge wang wu bian li 800mg tablet (力之源牌强劲威哥王五鞭粒)",
  "wei ge 99 2800mg capsule (偉哥99)",
  "baolong brand wu ye shen clalis capsule (寳龍牌五夜神胶囊)",
  "tian long brand te zhi wu ye shen sheng jing pian 2000mg tablet (天龙牌特制五夜神生精片)",
  "jin sheng li brand america brother 1000mg tablet (金聖力牌美国威哥王)",
  "jian min bao jian brand wolf 2000mg capsule (健民保健极品狼胶囊)",
  "li long brand wu di wei ge 2800mg capsule (力龙牌无敌伟哥)",
  "wake spray (金刚壹號)",
  "power 1 singapore brand chao nong suo pian weibawang 800mg (强劲威霸王五鞭粒)",
  "li long brand xi yu shen bao 2800mg tablet (力龙牌西域肾宝)",
  "xing ba wang capsule (性霸王)",
  "xi zang la sa 500mg tablet (西藏拉萨)",
  "ye tai yang jiao nang 1800mg (野太陽胶囊)",
  "baolong brand yilishen 2000mg tablet (寳龍牌蚁力神片剂)",
  "di liu dai yi pao dao tian liang 2000mg yan shi jiao nang (第六代一炮到天亮延时胶囊)",
  "yin de kuai 2280mg capsule (硬得快)",
  "ying xiong sheng li pian 800mg tablet (英雄生力片)",
  "yi li ting capsule (一粒挺)",
  "shen wei brand yi li wang 2000mg tablet (神威牌蚁力王)",
  "di er dai ye lang shen 2000mg capsule (第二代夜狼神)",
  "hong sheng brand ye ye bu dao 2500mg tablet (宏圣牌夜夜不倒)",
  "sheng yang brand yi li ok capsule (升阳牌一粒ok)",
  "sheng yang brand zhuang gen ying da wang 800mg tablet (升阳牌壯根硬大王)",
  "tian long brand yi li bo qian jin capsule (天龙牌一粒博千金)",
  "zengcuzengda yan shi pian 500mg tablet (增粗增大延时片)",
  "norethisterone",
  "kang li brand zhong hua niu bian 1500mg capsule (康力牌中华牛鞭 1500mg)",
  "sheng yang brand zhong hua niu bian 800mg tablet (升阳牌中华牛鞭)",
  "tian long brand di wu dai zhuang gen jing hua su sheng jing jiao nang 2000mg (天龙牌第五代壯根精华素生精胶囊)",
  "tianxiong brand zhuang yang wang 3000mg capsule (天雄牌壯陽王)",
  "sunny brand zang wang xiong ying capsule (陽光牌藏王雄鹰)",
  "xinyuan brand zang mi shen wei 1280mg capsule (鑫源牌藏秘神威）",
  "jin sheng li brand zhong hua niu bao1800mg pill (金聖力牌中華牛寳)",
  "aloe vera waste discharging & beauty 250mg capsule (芦荟排毒养颜胶囊)",
  "bo er gen 0.3g capsule (勃尔根胶囊)",
  "brazil basehr nuts 250mg capsule (第2代巴沙瘦身果)",
  "drpharm brand emperor capsule 0.5g (博龍牌黄帝聖丹膠囊)",
  "expressherbals no.1 mens supplement worldwide 500mg capsule",
  "yi li shen huichunruyi jiaonang 0.25g (1力神回春如意胶囊)",
  "aliba (阿里巴巴男士性功能专用)",
  "kangli bao jian niu bian da bu wan 1.5g (康力保健牛鞭大补丸 1.5g)",
  "heng yue brand jiu bian li 600mg tablet (恒悦牌九鞭粒)",
  "s-shape ii 0.3g capsule (瘦身の语 iii)",
  "stree overlord 4800mg capsule (街头霸王)",
  "mei guo xin yi dai shenliweige 2800mg capsule (美国新一代神力伟哥)",
  "sliming essence 500mg capsule (火速消脂精華膠囊)",
  "teng huang guo shou shen jin fu 0.3g capsule (藤黄果瘦身紧肤胶囊)",
  "vpxl 500mg capsule (white)",
  "shenwei brand maxman tablets 3800mg (神威牌 maxman 3800mg)",
  "ding xin brand yilishen 0.4g capsule (鼎鑫牌蚁力神胶囊)",
  "yu mei tang shou shen jin fu xian xian jian fei jiao nang 300mg (御美堂瘦身紧肤纤纤减肥胶囊(第三代加强型))",
  "zang jing dan (藏精丹)",
  "sheng yuan brand zang niu bian huo li jiao nang 800mg (圣源牌藏牛鞭活力胶囊)",
  "zhen de shou fat loss capsule 250mg (神仙叶牌真得瘦清脂胶囊)",
  "tian long brand di liu dai zhuang gen jing hua su sheng jing jiao nang 5000mg (天龙牌第六代壯根精华素生精胶囊)",
  "oto brand qing tian zhu capsule (oto擎天柱牌健力胶囊)",
  "qing guo su 0.35g capsule (青果素韵美姿减肥胶囊)",
  "kang bo si jian fei jiao nang 350mg (康柏丝减肥胶囊)",
  "li long brand ling tou lang 2800mg capsule (力龙牌领头狼)",
  "tianxiong brand lion usa 8000mg tablet (天雄牌美国雄狮)",
  "lnh solutions 500mg capsule",
  "shenwei brand san bian shen li wan 3800mg (神威牌三鞭神力丸3800mg)",
  "omax mutual slimming pills 0.3g (day) (澳美斯超能燃脂素瘦身丸(日间装))",
  "omax mutual slimming pills 0.3g (night) (澳美斯超能燃脂素瘦身丸(夜间装))",
  "maxgain+ 500mg capsule",
  "maxherbal no. 1 dietary supplement for men 500mg capsule",
  "liu mei brand natural slimming 450mg capsule (柳美牌自然瘦)",
  "tusuk jari asam urat untuk pria dan wanita capsule",
  "king brand black king 1800mg capsule (黑金刚)",
  "super-slim capsule (减肥果绿色瘦身胶囊)",
  "mmc mahman capsules (maxman 3000mg capsules)",
  "aidi brand wodibo capsule (艾迪牌五便宝胶囊)",
  "xp tongkat ali supreme for men 500mg capsule",
];

export default restrictedItems;
