# Generated by Django 4.1.7 on 2023-03-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="likes",
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
