# Generated by Django 4.1.7 on 2023-04-01 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0006_thread_offer_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pickupLocations",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(default="No Description"),
        ),
        migrations.AlterField(
            model_name="product", name="notes", field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profilepic", models.ImageField(blank=True, null=True, upload_to="")),
                ("bio", models.TextField(blank=True, null=True)),
                ("telegram", models.CharField(max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerProfile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
