# Generated by Django 4.1.7 on 2023-04-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_profile"),
    ]

    operations = [
        migrations.DeleteModel(name="Profile",),
    ]
