# Generated by Django 4.1.7 on 2023-04-01 10:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0012_rename_profile_userprofile"),
    ]

    operations = [
        migrations.RenameModel(old_name="Userprofile", new_name="Profile",),
    ]
