# Generated by Django 4.1.7 on 2023-04-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_rename_userprofile_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="isReviewedBuyer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="isReviewedSeller",
            field=models.BooleanField(default=False),
        ),
    ]
