# Generated by Django 4.2 on 2023-04-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_userprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='isBookmarked',
        ),
    ]
