# Generated by Django 4.2 on 2023-04-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_bookmark_product_alter_bookmark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
    ]
